[package]
name = "transformer-typ"
version = "0.1.0"
edition = "2021"

[lib]
name = "transformer_typ"
crate-type = ["cdylib"]

[dependencies]
typst = "0.14.0"
tokio = { version = "1.42.0", features = ["full"] }
pyo3 = { version = "0.27.0", features = ["extension-module"] }